services:
  weatheryzer-function:
    build:
      context: .
      dockerfile: Weatheryzer.API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__PostgreSQL=Server=postgres;Port=5432;Database=weatheryzer;User Id=postgres;Password=admin;
    depends_on:
      - postgres
      - seq

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
        

volumes:
  postgres_data: